const $=id=>document.getElementById(id);
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'Request failed');e.status=r.status;throw e}return d}
function val(id){return $(id)?.value||''}
async function load(){try{const s=await api('/admin/api/settings');const v=s.settings?.verification||{},sh=v.shorteners||{},se=s.settings?.search||{};$('verifyEnabled').checked=!!v.enabled;$('shortlinkEnabled').checked=v.shortlink_mode!=='disabled';$('s1on').checked=!!sh['1']?.enabled;$('s2on').checked=!!sh['2']?.enabled;$('s3on').checked=!!sh['3']?.enabled;$('s1name').value=sh['1']?.name||'';$('s1api').value=sh['1']?.api||'';$('s2name').value=sh['2']?.name||'';$('s2api').value=sh['2']?.api||'';$('s3name').value=sh['3']?.name||'';$('s3api').value=sh['3']?.api||'';$('t1').value=v.tutorial_1||'';$('t2').value=v.tutorial_2||'';$('t3').value=v.tutorial_3||'';$('v2').value=v.verification_time_2||0;$('v3').value=v.verification_time_3||0;$('validity').value=v.validity_hours||24;$('maintenance').checked=!!s.settings?.site?.maintenance;$('maxResults').value=se.max_results||20;$('resultsPerPage').value=se.results_per_page||20;$('candidateLimit').value=se.candidate_limit||120;$('spellCheck').checked=se.spell_check!==false;$('fuzzy').checked=se.fuzzy_fallback!==false;$('imdb').checked=!!se.imdb_poster;const f=s.settings?.files||{},m=s.settings?.metadata||{},pay=s.settings?.payments||{};$('fileSecure').checked=!!f.file_secure;$('autoDelete').checked=!!f.auto_delete;$('autoDeleteSeconds').value=f.auto_delete_seconds||60;$('tmdbEnabled').checked=!!m.tmdb_enabled;$('posterFallback').checked=m.poster_fallback!==false;$('activationMode').value=pay.activation_mode||'environment';$('premiumBypass').checked=pay.premium_bypass_verification!==false;$('state').textContent=JSON.stringify(s.settings,null,2);$('panel').classList.remove('hidden');await loadRequests()}catch(e){if(e.status===401){location.replace('/admin');return}$('state').textContent=e.message}}
$('logout').onclick=async()=>{await api('/admin/logout',{method:'POST'});location.reload()};$('refresh').onclick=load;
$('saveMaintenance').onclick=async()=>{await api('/admin/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({site:{maintenance:$('maintenance').checked}})});load()};
$('saveSearch').onclick=async()=>{await api('/admin/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({search:{max_results:Number(val('maxResults')||20),results_per_page:Number(val('resultsPerPage')||20),candidate_limit:Number(val('candidateLimit')||120),spell_check:$('spellCheck').checked,fuzzy_fallback:$('fuzzy').checked,imdb_poster:$('imdb').checked}})});load()};

$('saveFiles').onclick=async()=>{await api('/admin/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({files:{file_secure:$('fileSecure').checked,auto_delete:$('autoDelete').checked,auto_delete_seconds:Number(val('autoDeleteSeconds')||60)},metadata:{tmdb_enabled:$('tmdbEnabled').checked,poster_fallback:$('posterFallback').checked}})});load()};
$('saveVerify').onclick=async()=>{await api('/admin/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({verification:{enabled:$('verifyEnabled').checked,shortlink_mode:$('shortlinkEnabled').checked?'enabled':'disabled',shorteners:{'1':{enabled:$('s1on').checked,name:val('s1name'),api:val('s1api')},'2':{enabled:$('s2on').checked,name:val('s2name'),api:val('s2api')},'3':{enabled:$('s3on').checked,name:val('s3name'),api:val('s3api')}},tutorial_1:val('t1'),tutorial_2:val('t2'),tutorial_3:val('t3'),verification_time_2:Number(val('v2')||0),verification_time_3:Number(val('v3')||0),validity_hours:Number(val('validity')||24)}})});load()};
$('savePayments').onclick=async()=>{await api('/admin/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({payments:{activation_mode:val('activationMode'),premium_bypass_verification:$('premiumBypass').checked,premium_bypass_shortener:$('premiumBypass').checked}})});load()};
async function loadRequests(){try{const d=await api('/admin/api/premium/manual');const box=$('manualRequests');box.innerHTML='';if(!d.requests?.length){box.innerHTML='<p class="muted">No pending manual requests.</p>';return}d.requests.forEach(r=>{const el=document.createElement('div');el.className='request';el.innerHTML=`<b>${r.plan_name}</b> — ₹${r.amount}<br><small>User: ${r.user_id}<br>Request: ${r.id}</small><div><a target="_blank" href="/admin/api/premium/manual/${encodeURIComponent(r.id)}/proof">View proof</a> <button data-a="approve">Approve</button> <button data-a="reject">Reject</button></div>`;el.querySelectorAll('button').forEach(b=>b.onclick=async()=>{await api('/admin/api/premium/manual/decide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:r.id,action:b.dataset.a})});loadRequests()});box.append(el)})}catch(e){$('manualRequests').innerHTML=`<p class="muted">${e.message}</p>`}}
load();
