const $=id=>document.getElementById(id);let currentTitle=null,currentFile=null,currentRetry=null,homeData=null;
const toast=(msg)=>{const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}
function titleMeta(x){return [x.type==='series'?'Web Series':'Movie',x.year].filter(Boolean).join(' • ')}
function chip(item){const b=document.createElement('button');b.className='nameChip';b.innerHTML=`<strong>${esc(item.title)}</strong><small>${esc(titleMeta(item))}${item.count?` • ${item.count} files`:''}</small>`;b.onclick=()=>openTitle(item);return b}
function listItem(item){const b=document.createElement('button');b.className='nameItem';b.innerHTML=`<strong>${esc(item.title)}</strong><small>${esc(titleMeta(item))}</small>`;b.onclick=()=>openTitle(item);return b}
function renderHome(data){homeData=data;const items=data.items||[];const trend=items.slice(0,12),latest=items.slice(0,18),movies=items.filter(x=>x.type==='movie').slice(0,18),series=items.filter(x=>x.type==='series').slice(0,18);for(const [id,arr] of [['trending',trend],['latest',latest]]){$(id).innerHTML='';arr.forEach(x=>$(id).append(chip(x)))}for(const [id,arr] of [['movies',movies],['series',series]]){$(id).innerHTML='';arr.forEach(x=>$(id).append(listItem(x)))}const cats=new Set();items.forEach(x=>{if(x.type)cats.add(x.type==='series'?'Web Series':'Movies');(x.languages||x.audio_languages||[]).slice(0,4).forEach(v=>cats.add(v));});$('categories').innerHTML=[...cats].map(c=>`<button class="category" data-q="${esc(c)}">${esc(c)}</button>`).join('');$('categories').querySelectorAll('button').forEach(b=>b.onclick=()=>search(b.dataset.q));}
async function loadHome(){try{const d=await API.get('/api/home');renderHome(d)}catch(e){toast(e.message)}}
async function search(q){q=(q||'').trim();if(!q)return;show('searchSection');$('resultTitle').textContent=`Searching “${q}”…`;$('results').innerHTML='<p class="muted">Searching the real catalog…</p>';try{const d=await API.get(`/api/search?q=${encodeURIComponent(q)}`);$('resultTitle').textContent=`${d.count||0} result${d.count===1?'':'s'} found`;$('results').innerHTML='';if(!d.items?.length){$('results').innerHTML='<p class="muted">Nothing found. Try a simpler title or spelling.</p>';return}d.items.forEach(item=>{const row=document.createElement('div');row.className='resultItem';row.innerHTML=`<div class="resultMain"><div class="resultTitle">${esc(item.title)}</div><div class="resultMeta">${esc(titleMeta(item))}${item.description?` • ${esc(item.description)}`:''}</div></div><div class="resultAction"><button>Open</button></div>`;row.querySelector('button').onclick=()=>openTitle(item);$('results').append(row)})}catch(e){$('results').innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function openTitle(item){try{const d=await API.get(`/api/title/${encodeURIComponent(item.id)}`);currentTitle=d;renderDetail(d);show('detail')}catch(e){toast(e.message)}}
function renderDetail(d){const seasons=d.seasons||[];let html=`<div class="detail"><p class="detailKicker">${esc(d.type==='series'?'WEB SERIES':'MOVIE')}</p><h2>${esc(d.title)}${d.year?` <span class="muted">(${esc(d.year)})</span>`:''}</h2>${d.description?`<p class="detailDesc">${esc(d.description)}</p>`:''}`;
if(d.type==='series'){html+=`<div class="choiceGroup"><h3>Seasons</h3><div class="choices" id="seasonChoices">${seasons.map((s,i)=>`<button class="choice ${i===0?'active':''}" data-season="${s.season}">Season ${s.season}</button>`).join('')}</div></div><div class="choiceGroup"><h3>Episodes</h3><div class="episodeGrid" id="episodeChoices"></div></div>`}html+=`<div id="assetChoices"></div><div class="watchRow"><button class="watch" id="watchBtn">Watch Online</button><button class="download" id="downloadBtn">Download</button></div></div>`;$('detailBody').innerHTML=html;let selectedSeason=seasons[0]?.season||null,selectedEpisode=null,selectedLang=null,selectedQuality=null;
const renderAssets=()=>{const pool=d.type==='series'?(seasons.find(s=>s.season===selectedSeason)?.episodes||[]).flatMap(e=>e.variants||[]):(d.variants||[]);const langs=[...new Set(pool.flatMap(v=>v.languages||v.audio_languages||[]))];const quals=[...new Set(pool.map(v=>v.quality).filter(Boolean))];if(!selectedLang)selectedLang=langs[0]||null;if(!selectedQuality)selectedQuality=quals[0]||null;$('assetChoices').innerHTML=`<div class="choiceGroup"><h3>Language</h3><div class="choices">${langs.map(x=>`<button class="choice ${x===selectedLang?'active':''}" data-lang="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div class="choiceGroup"><h3>Quality</h3><div class="choices">${quals.map(x=>`<button class="choice ${x===selectedQuality?'active':''}" data-quality="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`;$('assetChoices').querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{selectedLang=b.dataset.lang;renderAssets()});$('assetChoices').querySelectorAll('[data-quality]').forEach(b=>b.onclick=()=>{selectedQuality=b.dataset.quality;renderAssets()});currentFile=pickFile(d,selectedSeason,selectedEpisode,selectedLang,selectedQuality);};
const renderEpisodes=()=>{if(d.type!=='series')return;const s=seasons.find(x=>x.season===selectedSeason);$('episodeChoices').innerHTML=(s?.episodes||[]).map((e,i)=>`<button class="episode ${i===0?'active':''}" data-ep="${e.episode}">E${String(e.episode).padStart(2,'0')}</button>`).join('');selectedEpisode=s?.episodes?.[0]?.episode||null;$('episodeChoices').querySelectorAll('[data-ep]').forEach(b=>b.onclick=()=>{selectedEpisode=Number(b.dataset.ep);$('episodeChoices').querySelectorAll('.episode').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedLang=null;selectedQuality=null;renderAssets()});renderAssets()};
$('seasonChoices')?.querySelectorAll('[data-season]').forEach(b=>b.onclick=()=>{selectedSeason=Number(b.dataset.season);selectedEpisode=null;selectedLang=null;selectedQuality=null;$('seasonChoices').querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderEpisodes()});renderEpisodes();if(d.type==='movie')renderAssets();
$('watchBtn').onclick=()=>access('watch');$('downloadBtn').onclick=()=>access('download');}
function pickFile(d,s,e,lang,quality){let pool=d.type==='series'?(d.seasons?.find(x=>x.season===s)?.episodes?.find(x=>x.episode===e)?.variants||[]):(d.variants||[]);return pool.find(v=>(!lang||(v.languages||v.audio_languages||[]).includes(lang))&&(!quality||String(v.quality).toLowerCase()===String(quality).toLowerCase()))||pool[0]||null}
async function access(mode){if(!currentFile){toast('Choose a real quality/language/episode first.');return}currentRetry=async info=>{openVerify(info,mode)};try{await Player.open(currentFile,mode,currentRetry)}catch(e){toast(e.message)}}
function openVerify(info,mode){$('verifyText').textContent=`Verification stage ${info.stage||1} is required before you can ${mode==='download'?'download':'watch'} this file.`;$('verifyLink').href=info.verification_url||'#';$('verifyLink').classList.toggle('hidden',!info.verification_url);$('telegramLink').classList.toggle('hidden',!info.telegram_url);if(info.telegram_url)$('telegramLink').href=info.telegram_url;$('tutorialLink').classList.toggle('hidden',!info.tutorial_url);if(info.tutorial_url)$('tutorialLink').href=info.tutorial_url;$('verifyState').textContent='After completing verification, return here and press “Check again”.';$('verifyRefresh').onclick=async()=>{try{const s=await API.get('/api/access-status');if(s.verified||s.premium){hide('verify');await Player.open(currentFile,mode,currentRetry)}else toast('Still waiting for verification.')}catch(e){toast(e.message)}};$('buyPremiumFromVerify').onclick=()=>{hide('verify');$('premiumSection').scrollIntoView({behavior:'smooth'})};show('verify')}
async function loadPremium(){try{const d=await API.get('/api/premium');$('premiumBadge').textContent=d.premium?`ACTIVE • ${new Date(d.expires_at*1000).toLocaleDateString()}`:'FREE';$('premiumCopy').textContent=d.premium?'Premium is active on this browser. Verification is bypassed while it remains active.':'Choose a plan if you want verification bypass while premium is active.';$('premiumPlans').innerHTML=(d.plans||[]).map(p=>`<div class="plan"><strong>${esc(p.name)}</strong><span>₹${esc(p.price_inr)}</span><button data-plan="${esc(p.id)}">Buy</button></div>`).join('');$('premiumPlans').querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>buyPlan(b.dataset.plan,d));if(d.provider==='manual'||d.provider==='both'){show('manualPay');$('manualInstructions').textContent=d.manual_instructions||'';$('manualPlan').innerHTML=(d.plans||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)} — ₹${esc(p.price_inr)}</option>`).join('');if(d.manual_qr){$('manualQr').src=d.manual_qr;show('manualQr')}}}catch(e){toast(e.message)}}
async function buyPlan(id,d){const p=d.plans.find(x=>x.id===id);if(!p)return;if(d.provider==='razorpay'||d.provider==='both'){try{const o=await API.post('/api/premium/order',{plan_id:id});if(!window.Razorpay){toast('Automatic payment UI is unavailable; use manual payment if enabled.');return}new Razorpay({key:o.key_id,amount:o.amount,currency:o.currency,name:'VYRA',description:p.name,order_id:o.order_id,handler:async r=>{await API.post('/api/premium/verify',{...r});toast('Premium activated');loadPremium()}}).open()}catch(e){toast(e.message)}}}
$('manualSubmit').onclick=async()=>{const f=$('premiumProof').files[0],plan=$('manualPlan').value;if(!f||!plan){toast('Select a plan and payment screenshot.');return;}const fd=new FormData();fd.append('proof',f);fd.append('plan_id',plan);fd.append('note',$('premiumNote').value);try{const r=await fetch('/api/premium/manual',{method:'POST',body:fd,credentials:'same-origin'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed');$('manualState').textContent=d.message||'Proof submitted.'}catch(e){toast(e.message)}};
$('homeSearch').onclick=()=>search($('homeQuery').value);$('homeQuery').onkeydown=e=>{if(e.key==='Enter')search(e.target.value)};$('searchBtn').onclick=()=>{$('homeQuery').focus();window.scrollTo({top:0,behavior:'smooth'})};$('clearSearch').onclick=()=>{hide('searchSection');$('results').innerHTML=''};$('homeBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('premiumBtn').onclick=()=>$('premiumSection').scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));
$('app').classList.remove('hidden');$('playerClose').onclick=()=>Player.close();(async()=>{loadHome();loadPremium()})();
